# Pantalla OLED
CONFIG_ZMK_DISPLAY=y

# Desactivar servicio de batería local (EVITA EL HARD FAULT)
CONFIG_BT_BAS=n

# Leer batería de las mitades por Bluetooth
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Mantener potencia de señal y evitar que se duerma el dongle
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SLEEP=n