# --- CONFIGURACIÓN SPLIT Y DONGLE ---
# Permitir la conexión simultánea de las 2 mitades al dongle
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
# Potencia de transmisión Bluetooth al máximo (+8dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Desactivar la suspensión (el dongle siempre se alimenta por USB)
CONFIG_ZMK_SLEEP=n

# --- CONFIGURACIÓN DE PANTALLA OLED ---
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_EXT_POWER=y

# EVITAR CRASH: Desactivar widgets que leen la batería local en el dongle
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n