# Habilitar Pantalla
CONFIG_ZMK_DISPLAY=y

# DESACTIVAR el widget de batería local para evitar el crash/Hard Fault en el dongle
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n

# Widgets seguros para el dongle (Capa activa y salida USB/BLE)
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# Opcional: desactivar WPM si da problemas de memoria
CONFIG_ZMK_WIDGET_WPM_STATUS=n